### ISSUE TITLE
always doesn't work 

### ISSUE THREAD

**Issue by idmytro** [ChrisShank/xstate-vue2#8] opened 2023-04-11 22:35 UTC
This simple machine doesn't work with xstate-vue2, but works with @xstate/vue

```ts
const simpleMachine = createMachine({
  id: 'simple',
  initial: 'idle',
  states: {
    idle: {
      always: [
        {actions: 'log', target: 'active'}
      ],
    },
    active: {}
  }
},
{
  actions: {
    log: () => console.log('log')
  }
})
```

**Comment by ChrisShank** [comment] 2023-04-12 17:18
Peculiar, I think I can reproduce this https://stackblitz.com/edit/vite-9wsjog?file=main.js

> Cannot set properties of undefined (setting 'value')

Seems like `listener` is called before the `state` variable is initialized. Should be easy to fix :)

**Comment by ChrisShank** [comment] 2023-04-13 04:58
Okay so this was a regression caused by the last [bug fix](https://github.com/ChrisShank/xstate-vue2/issues/6). `@xstate/vue` doesn't have this bug because that other bug hasn't been patched. I'll try to fix this regression tomorrow, thanks for reporting!

**Comment by daniel-n-dream** [comment] 2023-04-23 20:19
I also get the error `Cannot set properties of undefined (setting 'value')` with a Machine that uses Always transitions a lot, is there any possible workaround or update on this @ChrisShank ?

**Comment by ChrisShank** [comment] 2023-04-24 03:33
Fixed in v0.3.2

See the reproducer with the latest version https://stackblitz.com/edit/vite-vqm8hy?file=package.json

**Closed as completed by ChrisShank** 2023-04-24 03:33 UTC
